### ISSUE TITLE
yolov5 段错误 context.enqueue(batchSize, buffers, stream, nullptr);

### ISSUE THREAD

**Issue by TimLiujn** [wang-xinyu/tensorrtx#101]
/usr/bin/ld: warning: libcudart.so.10.0, needed by /usr/local/TensorRT-6.0.1.5/lib/libnvinfer.so, may conflict with libcudart.so.10.2
[100%] Built target yolov5s
[07/22/2020-14:15:25] [W] [TRT] TensorRT was linked against cuDNN 7.6.3 but loaded cuDNN 7.6.0
[07/22/2020-14:15:25] [W] [TRT] TensorRT was linked against cuDNN 7.6.3 but loaded cuDNN 7.6.0
0x7ffc5c6b83e0	0x7fba5702f056	1
段错误 (核心已转储)

**Comment by wang-xinyu** [comment]
环境有问题，tensorrt是cuda10.0的，环境是10.2

**Comment by TimLiujn** [comment]
> 环境有问题，tensorrt是cuda10.0的，环境是10.2

我本机环境是cuda10.0，tensorrt版本是6.0.1.5，您说的这个环境指的是哪个环境，程序要求的环境吗

**Comment by wang-xinyu** [comment]
报错里面写的，环境里面有cuda10.2，然后tensorrt是link到cudnn7.6.3的，所以环境有问题。
不是程序要求的环境，是系统环境，cuda、cudnn、tensorrt三个，版本没对上。

**Comment by TimLiujn** [comment]
> 环境有问题，tensorrt是cuda10.0的，环境是10.2

解决了，万分感谢
