### ISSUE TITLE
 ./yolov5_det -s yolov5s.wts yolov5s.engine s   Could not load library libcublasLt.so.12

### ISSUE THREAD

**Issue by zxjt2012** [wang-xinyu/tensorrtx#1262]
build$ ./yolov5_det -s yolov5s.wts yolov5s.engine s
[03/12/2023-23:22:46] [W] [TRT] The implicit batch dimension mode has been deprecated. Please create the network with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag whenever possible.
Loading weights: yolov5s.wts
Building engine, please wait for a while...
Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory
已放弃 (核心已转储)

cuda 11.7
显卡 3060
tensorrt '8.5.3.1'

**Comment by wang-xinyu** [comment]
tensorrt 要和cuda版本对应，试试低版本的

**Comment by zxjt2012** [comment]
确实是版本问题，已解决。

**Comment by Mr-MoNET** [comment]
![94d8813d4f931195e03cc3b5a41cbf8](https://github.com/wang-xinyu/tensorrtx/assets/48426139/8bceabfd-11a7-4375-9aa7-d5d085bf2229)
大佬，为什么我在转换engine文件的时候，没有任何报错，但是无法转换engine文件。上面的是一张图片，我在cmd环境下输入命令后，程序开始运行，当显示完load weights：best.wts的时候，程序直接中断了，没有输出"building engine"的字样，请问大佬这是什么问题，我查了谷歌和必应也没找出问题所在。

显卡 RTX 2070
cuda 11.6
TensorRT 8.6.1.6
模型 yolov5n.pt

**Comment by wang-xinyu** [comment]
@Mr-MoNET 如果问题还在，就再创建一个新的issue吧
