### ISSUE TITLE
导出retinaface的engine时候报错

### ISSUE THREAD

**Issue by afterimagex** [wang-xinyu/tensorrtx#174]
我的环境是这样的（docker）:
ubuntu16.04
cuda9.0
tensorrt4.0
cudnn7.6.4
pytorch1.5

生成wts都一切正常，但是在运行retina_50 -s 的时候报错：

```
set name out, start building trt engine...
ERROR: cudnnConvolutionLayer.cpp (161) - Cudnn Error in execute: 8
ERROR: cudnnConvolutionLayer.cpp (161) - Cudnn Error in execute: 8
build out
retina_50: /code/tensorrtx/retinaface/retina_r50.cpp:417: void APIToModel(unsigned int, nvinfer1::IHostMemory**): Assertion `engine != nullptr' failed.
Aborted (core dumped)
```

发生错误的代码段

```
ICudaEngine* engine = builder->buildCudaEngine(*network);
```

我已经切换到trt4分支了，但是依然无正常运行，请教一下我这个问题如何解决。

**Comment by wang-xinyu** [comment]
应该是cudnn版本和trt版本不匹配

**Comment by afterimagex** [comment]
> 应该是cudnn版本和trt版本不匹配

非常感谢，应该是这个问题了。

**Comment by afterimagex** [comment]
> 应该是cudnn版本和trt版本不匹配

大佬。。我发现我依然无法解决这个问题，我把cudnn7.1.3 、7.1.4 、7.6.* 都试了。依然存在这个错误，我下载的tensorrt为：TensorRT-4.0.1.6.Ubuntu-16.04.4.x86_64-gnu.cuda-9.0.cudnn7.1.tar.gz

链接库看起来也是正常的：
![image](https://user-images.githubusercontent.com/17892974/92672414-35448080-f34b-11ea-85c1-22afc2e9b4ed.png)

实在是希望解决这个问题，谢谢了。

**Comment by wang-xinyu** [comment]
建议安装deb包，不要用tar，deb可以自己解决依赖问题

**Comment by afterimagex** [comment]
> 建议安装deb包，不要用tar，deb可以自己解决依赖问题

谢谢，再次感谢！

**Comment by yanghgai** [comment]
> > 建议安装deb包，不要用tar，deb可以自己解决依赖问题
> 
> 谢谢，再次感谢！

请问解决了吗？ 我也遇到了这个问题

**Comment by 1156103715** [comment]
请问问题解决了了吗 我也遇到这个问题了

**Comment by zbyuan** [comment]
请问问题解决了了吗 我也遇到这个问题了
