### ISSUE TITLE
ValueError: could not broadcast input array from shape (1107168) into shape (1108992)

### ISSUE THREAD

**Issue by llzhaoshuo** [wang-xinyu/tensorrtx#176]
使用自己的数据集训练出来的模型，在使用trt时只修改了类别数和anchor，输入均为608*608，报错如下：

python yolov5_trt.py
[TensorRT] WARNING: Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/lzs/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "yolov5_trt.py", line 271, in run
    self.func(*self.args)
  File "yolov5_trt.py", line 120, in infer
    np.copyto(host_inputs[0], input_image.ravel())
  File "<__array_function__ internals>", line 6, in copyto
ValueError: could not broadcast input array from shape (1107168) into shape (1108992)

-------------------------------------------------------------------
PyCUDA ERROR: The context stack was not empty upon module cleanup.
-------------------------------------------------------------------
A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.
-------------------------------------------------------------------
Aborted (core dumped)
是还需要修改其他地方吗？

**Comment by wang-xinyu** [comment]
先试试c++程序能否跑通

**Comment by llzhaoshuo** [comment]
> 先试试c++程序能否跑通

mkdir build
cd build
cmake ..
make
sudo ./yolov5 -s
sudo ./yolov5 -d  ../samples
运行到最后行都没有问题

**Comment by wang-xinyu** [comment]
如果c++能跑通，python代码应该没问题，可以自己调试看看，

**Comment by llzhaoshuo** [comment]
> 如果c++能跑通，python代码应该没问题，可以自己调试看看，

在yolov5_trt.py中，290行的input_image_paths = ["zidane.jpg", "bus.jpg"]，我将readme中的图片下载下来用于测试就没有任何问题，将这两个.jpg换成我自己的图片就会出现上面的问题。
所以这个是和图片的分辨率有关系吗？

**Comment by AirFishWang** [comment]
python脚本处理图片的尺寸有点小问题，最终输入的尺寸不一定等于网络的输入大小，你可以调试一下

**Comment by DawnWalker** [comment]
@llzhaoshuo 我遇到和您一样的问题，请问您解决了吗？

**Comment by wang-xinyu** [comment]
```
image = cv2.copyMakeBorder( 
     image, ty, ty, tx, tx, cv2.BORDER_CONSTANT, (128, 128, 128)) 
```
这里不能用ty，ty，tx，tx，做个减法就好了INPUT_H - th -ty

**Comment by sudapure** [comment]
@wang-xinyu , i tried this issue with the latest [bug fix](https://github.com/wang-xinyu/tensorrtx/commit/9cca2bd205471f74f23746b93097fb39482bc8af) commit, but i am still getting the same error.
