### ISSUE TITLE
sudo ./yolov4 -s

### ISSUE THREAD

**Issue by yangtao19920109** [wang-xinyu/tensorrtx#257]
[10/27/2020-10:26:59] [F] [TRT] Assertion failed: cublasStatus == CUBLAS_STATUS_SUCCESS
../rtSafe/cublas/cublasLtWrapper.cpp:279
Aborting...
[10/27/2020-10:27:00] [E] [TRT] ../rtSafe/cublas/cublasLtWrapper.cpp (279) - Assertion Error in getCublasLtHeuristic: 0 (cublasStatus == CUBLAS_STATUS_SUCCESS)
build out
yolov4: /home/yang/disk/tensorrt/tensorrtx/yolov4/yolov4.cpp:523: void APIToModel(unsigned int, nvinfer1::IHostMemory**): Assertion `engine != nullptr' failed.
已放弃 (核心已转储)

Is that the envriment problerm?

**Comment by XeonHis** [comment]
I have the same problem 
`Loading weights: ../yolov5s.wts
Building engine, please wait for a while...
[10/28/2020-23:24:28] [F] [TRT] Assertion failed: cublasStatus == CUBLAS_STATUS_SUCCESS
../rtSafe/cublas/cublasLtWrapper.cpp:279
Aborting...
[10/28/2020-23:24:28] [E] [TRT] ../rtSafe/cublas/cublasLtWrapper.cpp (279) - Assertion Error in getCublasLtHeuristic: 0 (cublasStatus == CUBLAS_STATUS_SUCCESS)
Build engine successfully!
yolov5: /home/paul/Desktop/utils/yolov5.cpp:396: void APIToModel(unsigned int, nvinfer1::IHostMemory**): Assertion `engine != nullptr' failed.
Aborted
`
and it seems that libcublas.so.10 is linked to /usr/lib/x86_64-linux-gnu/libcublas.so.10

this is the output of ldd yolov5 | grep libcu
`libcudart.so.10.2 => /usr/local/cuda/lib64/libcudart.so.10.2 (0x00007f422bb6e000)
libcudnn.so.8 => /usr/lib/x86_64-linux-gnu/libcudnn.so.8 (0x00007f4229e44000)
libcublas.so.10 => /usr/lib/x86_64-linux-gnu/libcublas.so.10 (0x00007f42206bc000)
libcublasLt.so.10 => /usr/lib/x86_64-linux-gnu/libcublasLt.so.10 (0x00007f421e829000)
libcurl-gnutls.so.4 => /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007f4217af9000)`

**Comment by wang-xinyu** [comment]
The cuda version and the tensorrt version must match.

Because trt need to link cuda.

For example, if your trt is built on cuda10.0, then you must use 10.0 not 10.2.

You can refer to the install tutorial in this repo.

**Comment by bamboosdu** [comment]
cuda version
```
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

```
cudnn version
```
dpkg -l | grep cuda
ii  libcudnn8                                     8.0.4.30-1+cuda10.2                              amd64        cuDNN runtime libraries
ii  libcudnn8-dev                                 8.0.4.30-1+cuda10.2                              amd64        cuDNN development libraries and headers
ii  libcudnn8-samples                             8.0.4.30-1+cuda10.2                              amd64        cuDNN documents and samples

```
tensorRT version
```
TensorRT-7.2.1.6.Ubuntu-18.04.x86_64-gnu.cuda-10.2.cudnn8.0.tar.gz
```
But I still meet the same problem

```

**Comment by wang-xinyu** [comment]
@bamboosdu 7.2 should also work.

you can try `ldd yolov4` to check the link libs.

**Comment by bamboosdu** [comment]
Thanks for your quick reply!
```
ldd yolov5
	linux-vdso.so.1 (0x00007fff82341000)
	libnvinfer.so.7 => /home/zq/Documents/TensorRT-7.2.1.6/lib/libnvinfer.so.7 (0x00007f28ac8e5000)
	libcudart.so.10.2 => /usr/local/cuda-10.2/lib64/libcudart.so.10.2 (0x00007f28ac667000)
	libmyplugins.so (0x00007f28ac459000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f28ac1f1000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f28abfbf000)
	libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007f28abd48000)
	libjasper.so.1 => /usr/lib/x86_64-linux-gnu/libjasper.so.1 (0x00007f28abaf3000)
	libtbb.so.2 => /usr/lib/x86_64-linux-gnu/libtbb.so.2 (0x00007f28ab8b7000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f28ab69a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f28ab496000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f28ab277000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f28ab06f000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f28aade3000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f28aaa5a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f28aa6bc000)
	libmvec.so.1 => /lib/x86_64-linux-gnu/libmvec.so.1 (0x00007f28aa492000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f28aa27a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f28a9e89000)
	libcudnn.so.8 => /usr/local/cuda-10.2/lib64/libcudnn.so.8 (0x00007f28a9c59000)
	libmyelin.so.1 => /home/zq/Documents/TensorRT-7.2.1.6/lib/libmyelin.so.1 (0x00007f28a93dd000)
	libnvrtc.so.10.2 => /usr/local/cuda-10.2/lib64/libnvrtc.so.10.2 (0x00007f28a7c30000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f28beb18000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f28a7a0a000)
	libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 (0x00007f28a77fc000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f28a75cb000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f28a7315000)
	libcublas.so.10 => /usr/lib/x86_64-linux-gnu/libcublas.so.10 (0x00007f28a305f000)
	libcublasLt.so.10 => /usr/lib/x86_64-linux-gnu/libcublasLt.so.10 (0x00007f28a11cc000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f28a0e94000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f28a0c6c000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f28a0a68000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f28a0862000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f28a064d000)
```
And the error is in **sudo ./yolov5 -s***
```
sudo ./yolov5 -s
Loading weights: ../yolov5m.wts
Building engine, please wait for a while...
[11/10/2020-14:13:57] [W] [TRT] TensorRT was linked against cuDNN 8.0.4 but loaded cuDNN 8.0.2
[11/10/2020-14:14:27] [F] [TRT] Assertion failed: cublasStatus == CUBLAS_STATUS_SUCCESS
../rtSafe/cublas/cublasLtWrapper.cpp:279
Aborting...
[11/10/2020-14:14:27] [E] [TRT] ../rtSafe/cublas/cublasLtWrapper.cpp (279) - Assertion Error in getCublasLtHeuristic: 0 (cublasStatus == CUBLAS_STATUS_SUCCESS)
Build engine successfully!
yolov5: /home/zq/zq/detection_v5/detection_segmentation/detection/yolov5.cpp:440: void APIToModel(unsigned int, nvinfer1::IHostMemory**): Assertion `engine != nullptr' failed.
[1]    32005 abort      sudo ./yolov5 -s
```

**Comment by wang-xinyu** [comment]
```
	libcudart.so.10.2 => /usr/local/cuda-10.2/lib64/libcudart.so.10.2 (0x00007f28ac667000)
	libcublas.so.10 => /usr/lib/x86_64-linux-gnu/libcublas.so.10 (0x00007f28a305f000)
```

your cuda is not right, 10.0 in `/usr/lib/x86_64-linux-gnu`,  10.2 in ` /usr/local/cuda-10.2/lib64`

**Comment by KevS272** [comment]
Hi everyone,

I'm running into the same problem:

> ```
> 	libcudart.so.10.2 => /usr/local/cuda-10.2/lib64/libcudart.so.10.2 (0x00007f28ac667000)
> 	libcublas.so.10 => /usr/lib/x86_64-linux-gnu/libcublas.so.10 (0x00007f28a305f000)
> ```
> 
> your cuda is not right, 10.0 in `/usr/lib/x86_64-linux-gnu`, 10.2 in ` /usr/local/cuda-10.2/lib64`

How can I change the links so that it uses the correct libraries?
in /usr/lib/x86_64-linux-gnu/ there are both libcublas.so.10 and libcublas.so.10.2.2.89 

thx in advance!

**Comment by KevS272** [comment]
> Hi everyone,
> 
> I'm running into the same problem:
> 
> > ```
> > 	libcudart.so.10.2 => /usr/local/cuda-10.2/lib64/libcudart.so.10.2 (0x00007f28ac667000)
> > 	libcublas.so.10 => /usr/lib/x86_64-linux-gnu/libcublas.so.10 (0x00007f28a305f000)
> > ```
> > 
> > 
> > your cuda is not right, 10.0 in `/usr/lib/x86_64-linux-gnu`, 10.2 in ` /usr/local/cuda-10.2/lib64`
> 
> How can I change the links so that it uses the correct libraries?
> in /usr/lib/x86_64-linux-gnu/ there are both libcublas.so.10 and libcublas.so.10.2.2.89
>... or do I have to downgrade to CUDA 10.0 to use it properly? 
>
> thx in advance!

**Comment by wang-xinyu** [comment]
sorry I made a mistake. libcublas.so.10 is a soft link to libcublas.so.10.2.2.89.
so cublas is no problem.
Your cudnn may not right.
please try following the install tutorial, and install the tensorrt .deb package, which also contains cudnn.

**Comment by superMC5657** [comment]
It's great work!!!
Maybe not supporttensorrt 7.2.1.6,  I change the version to 7.1.3.4.
my all  envs version,  cuda10.2 cudnn8.0 tensorrt7.1.3.4

**Comment by oyrq** [comment]
From NVIDIA reply:
TRT 7.2.1 switches to use cuBLASLt (previously it was cuBLAS). cuBLASLt is the defaulted choice for SM version >= 7.0. However,you may need CUDA-10.2 Patch 1 (Released Aug 26, 2020) 6 to resolve some cuBLASLt issues. Another option is to use the new TacticSource 4 API and disable cuBLASLt tactics if you dont want to upgrade.

[https://forums.developer.nvidia.com/t/matrixmultiply-failed-on-tensorrt-7-2-1/158187/5](url)

**Comment by bot66** [comment]
> From NVIDIA reply:
> TRT 7.2.1 switches to use cuBLASLt (previously it was cuBLAS). cuBLASLt is the defaulted choice for SM version >= 7.0. However,you may need CUDA-10.2 Patch 1 (Released Aug 26, 2020) 6 to resolve some cuBLASLt issues. Another option is to use the new TacticSource 4 API and disable cuBLASLt tactics if you dont want to upgrade.
> It's great work!!!
> [https://forums.developer.nvidia.com/t/matrixmultiply-failed-on-tensorrt-7-2-1/158187/5](url)

and don't forget add /usr/local/cuda-10.2/lib64 to /etc/ld.so.conf and run ldconfig as root

**Comment by O2andsAnoxia** [comment]
Hi everyone,It's really the CUDNN that causes the problem
I meet the same problem with you,my original envs are CUDA10.2 CUDNN8.0.4 TRT 7.2.2.3 and the problem are same with @bamboosdu .I download a new TRT 7.1.3.4 accordingly @superMC,but the problem are existing.So i update CUDNN to 8.0.5 accordingly the first [W],the problem was solved.

**Comment by xugesheng** [comment]
> I have the same problem
> `Loading weights: ../yolov5s.wts Building engine, please wait for a while... [10/28/2020-23:24:28] [F] [TRT] Assertion failed: cublasStatus == CUBLAS_STATUS_SUCCESS ../rtSafe/cublas/cublasLtWrapper.cpp:279 Aborting... [10/28/2020-23:24:28] [E] [TRT] ../rtSafe/cublas/cublasLtWrapper.cpp (279) - Assertion Error in getCublasLtHeuristic: 0 (cublasStatus == CUBLAS_STATUS_SUCCESS) Build engine successfully! yolov5: /home/paul/Desktop/utils/yolov5.cpp:396: void APIToModel(unsigned int, nvinfer1::IHostMemory**): Assertion `engine !=nullptr' failed.Aborted
> `
> and it seems that libcublas.so.10 is linked to /usr/lib/x86_64-linux-gnu/libcublas.so.10
> 
> this is the output of ldd yolov5 | grep libcu
> `libcudart.so.10.2 => /usr/local/cuda/lib64/libcudart.so.10.2 (0x00007f422bb6e000) libcudnn.so.8 => /usr/lib/x86_64-linux-gnu/libcudnn.so.8 (0x00007f4229e44000) libcublas.so.10 => /usr/lib/x86_64-linux-gnu/libcublas.so.10 (0x00007f42206bc000) libcublasLt.so.10 => /usr/lib/x86_64-linux-gnu/libcublasLt.so.10 (0x00007f421e829000) libcurl-gnutls.so.4 => /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007f4217af9000)`



I have the same problem. Have you solved it？

**Comment by serser** [comment]
I'm using CUDA10.2 + Patch 1 & 2 following [CUDA 10.2 Installation](https://developer.nvidia.com/cuda-10.2-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1604&target_type=deblocal) CUDNN 8.1.1, which TensorRT 7.2.3.4 is said to support. The error remains,

```
Building engine, please wait for a while...
[04/19/2021-15:50:30] [F] [TRT] Assertion failed: cublasStatus == CUBLAS_STATUS_SUCCESS
../rtSafe/cublas/cublasLtWrapper.cpp:279
Aborting...
[04/19/2021-15:50:30] [E] [TRT] ../rtSafe/cublas/cublasLtWrapper.cpp (279) - Assertion Error in getCublasLtHeuristic: 0 (cublasStatus == CUBLAS_STATUS_SUCCESS)
Build engine successfully!
yolov5: /home/guest-heuorb/zhangbo97/tensorrtx_weixin/yolov5/yolov5.cpp:1249: void APIToModel(unsigned int, nvinfer1::IHostMemory**): Assertion `engine != nullptr' failed.
Aborted (core dumped)
```

My `ldd yolov5` goes like,
```
$ ldd yolov5
	linux-vdso.so.1 =>  (0x00007fffb278c000)
	libnvinfer.so.7 => /home/guest-heuorb/cuda/TensorRT-7.2.3.4/lib/libnvinfer.so.7 (0x00007fb773111000)
	libcudart.so.10.2 => /usr/local/cuda/lib64/libcudart.so.10.2 (0x00007fb772e93000)
	libmyplugins.so => /home/guest-heuorb/zhangbo97/tensorrtx_weixin/yolov5/build_leakyrelu/libmyplugins.so (0x00007fb772c89000)
	libopencv_dnn.so.4.5 => /usr/local/lib/libopencv_dnn.so.4.5 (0x00007fb77263e000)
	libopencv_imgcodecs.so.4.5 => /usr/local/lib/libopencv_imgcodecs.so.4.5 (0x00007fb7722e7000)
	libopencv_imgproc.so.4.5 => /usr/local/lib/libopencv_imgproc.so.4.5 (0x00007fb770586000)
	libopencv_core.so.4.5 => /usr/local/lib/libopencv_core.so.4.5 (0x00007fb76f3dd000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb76effa000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb76ecf1000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb76ead9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb76e70f000)
	libcudnn.so.8 => /usr/lib/x86_64-linux-gnu/libcudnn.so.8 (0x00007fb76e4e5000)
	libmyelin.so.1 => /home/guest-heuorb/cuda/TensorRT-7.2.3.4/lib/libmyelin.so.1 (0x00007fb76dc69000)
	libnvrtc.so.10.2 => /usr/local/cuda/lib64/libnvrtc.so.10.2 (0x00007fb76c4bc000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb76c2b4000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb76c0b0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb784488000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb76be93000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007fb76bc3a000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fb76ba15000)
	libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007fb76b7a0000)
	libIlmImf-2_2.so.22 => /usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22 (0x00007fb76b2d0000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb76b0b6000)
	libcublas.so.10 => /usr/lib/x86_64-linux-gnu/libcublas.so.10 (0x00007fb766e00000)
	libcublasLt.so.10 => /usr/lib/x86_64-linux-gnu/libcublasLt.so.10 (0x00007fb764f6d000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fb764d4b000)
	libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 (0x00007fb764b3d000)
	libHalf.so.12 => /usr/lib/x86_64-linux-gnu/libHalf.so.12 (0x00007fb7648fa000)
	libIex-2_2.so.12 => /usr/lib/x86_64-linux-gnu/libIex-2_2.so.12 (0x00007fb7646dc000)
	libIlmThread-2_2.so.12 => /usr/lib/x86_64-linux-gnu/libIlmThread-2_2.so.12 (0x00007fb7644d5000)
``` 

CUBLAS and CUBLALT seems alright too,

```
$ ll /usr/lib/x86_64-linux-gnu/libcublas.so.10
lrwxrwxrwx 1 root root 22 Nov 14  2019 /usr/lib/x86_64-linux-gnu/libcublas.so.10 -> libcublas.so.10.2.2.89
$ ll /usr/lib/x86_64-linux-gnu/libcublasLt.so.10
lrwxrwxrwx 1 root root 24 Nov 14  2019 /usr/lib/x86_64-linux-gnu/libcublasLt.so.10 -> libcublasLt.so.10.2.2.89
```

I've added `/usr/local/cuda-10.2/lib64` to `/etc/ld.so.conf ` as @bot66 said. What am I missing? Please help.

**Comment by wang-xinyu** [comment]
@serser what's the full name of your TensorRT install pkg?

**Comment by serser** [comment]
> @serser what's the full name of your TensorRT install pkg?

I use `nv-tensorrt-repo-ubuntu1604-cuda10.2-trt7.2.3.4-ga-20210226_1-1_amd64.deb`.

**Comment by O2andsAnoxia** [comment]
> > @serser what's the full name of your TensorRT install pkg?
> 
> I use `nv-tensorrt-repo-ubuntu1604-cuda10.2-trt7.2.3.4-ga-20210226_1-1_amd64.deb` and the tarball is `TensorRT-7.2.3.4.Ubuntu-16.04.x86_64-gnu.cuda-10.2.cudnn8.1.tar.gz`.

Hi serser,i have the same problem with you in my another computer.My install pkg is nv-tensorrt-repo-ubuntu1804-cuda10.2-trt7.2.3.4-ga-20210226_1-1_amd64.deb.If you solved this problem.could you tell you how to do.It's my email 1766529899@qq.com, maybe we can discuss about it!

**Comment by serser** [comment]
@O2andsAnoxia One thing I am sure is that downgrading to CUDA10.0 with the corresponding TensorRT version certainly works.

**Comment by nabang1010** [comment]
> From NVIDIA reply: TRT 7.2.1 switches to use cuBLASLt (previously it was cuBLAS). cuBLASLt is the defaulted choice for SM version >= 7.0. However,you may need CUDA-10.2 Patch 1 (Released Aug 26, 2020) 6 to resolve some cuBLASLt issues. Another option is to use the new TacticSource 4 API and disable cuBLASLt tactics if you dont want to upgrade. It's great work!!! [https://forums.developer.nvidia.com/t/matrixmultiply-failed-on-tensorrt-7-2-1/158187/5](url)

Thanks @oyrq and  @bot66, It sloved my problem <3
