### ISSUE TITLE
Get Different results of arcface-mobilefacenet from TensorRT and Insightface(MXNet)

### ISSUE THREAD

**Issue by irvingzhang0512** [wang-xinyu/tensorrtx#559]
## Env

- GPU, 1080ti
- OS, Ubuntu16.04
- Cuda TensorRT -> 11.0, MXNet -> 10.1 
- TensorRT 7.2.2.3

## About this repo

- which branch/tag/commit are you using?
master

- which model?
arcface-mobilefacenet

## Your problem

Get DIFFERENT results from tensorrt and insightface(mxnet) arcface-mobilefacenet

Generate engine file without FP16 & INT8. And model inputs are

```cpp
    static float data[BATCH_SIZE * 3 * INPUT_H * INPUT_W];
    for (int i = 0; i < 3 * INPUT_H * INPUT_W; i++)
       data[i] = (1.0 - 127.5) * 0.0078125;
```

MXNet test code

```python
import mxnet as mx
import numpy as np

INPUT_NAME = "data"

def _test_with_mxnet(inputs,
                     model_prefix,
                     epoch,
                     image_size=(112, 112),
                     ctx=mx.gpu(0)):
    sym, arg_params, aux_params = mx.model.load_checkpoint(model_prefix, epoch)
    model = mx.mod.Module(symbol=sym, context=ctx, label_names=None)
    model.bind(data_shapes=[(INPUT_NAME, (1, 3) + image_size)])
    model.set_params(arg_params, aux_params)
    data = mx.nd.array(inputs)
    db = mx.io.DataBatch(data=(data, ))
    model.forward(db, is_train=False)
    return model.get_outputs()[0].asnumpy()

if __name__ == '__main__':
    import numpy as np

    model_prefix = "../data/model-y1-test2/model"
    epoch = 0
    image_size = (112, 112)
    dtype = "float32"
    # `- 127.5` and ` * 0.0078125` are included in model
    inputs = np.ones((1, 3) + image_size, dtype)

    print(
        _test_with_mxnet(inputs, model_prefix, epoch,
                         image_size).reshape(-1)[:10])
```

Results(First 10 elements, without l2 norm)
TensorRT: 0.0137709, -0.437659, -0.0656291, 0.75324, -0.119271, 0.0696135, -0.167614, -0.167495, 0.0333918, -0.213255
MXNet: [ 0.01727611 -0.42228088 -0.07166057  0.71358633 -0.12447033  0.06586611  -0.16812296 -0.13903154  0.04360449 -0.22122541]

**Comment by wang-xinyu** [comment]
@ybw108 pls take a look.

@irvingzhang0512 how about r50? Did you get same results?

**Comment by irvingzhang0512** [comment]
@wang-xinyu will have a try tomorrow

**Comment by irvingzhang0512** [comment]
@wang-xinyu @ybw108 
Test arcface-r50 and arcface-r100, the results of tensorrt and mxnet are almost the same.

The first 10 elements are listed as follows

```
mobilefacenet
mxnet
0.01727611 -0.42228088 -0.07166057  0.71358633 -0.12447033  0.06586611 -0.16812296 -0.13903154  0.04360449 -0.22122541
tensorrt
0.0137709, -0.437659, -0.0656291, 0.75324, -0.119271, 0.0696135, -0.167614, -0.167495, 0.0333918, -0.213255, 

r50
mxnet
-0.22546756  0.04918719 -0.3623678  -0.2190522  -0.24733274 -0.21455336 0.16517986  0.05563676  0.09002142  0.14286046
tensorrt
-0.225467, 0.0491875, -0.362366, -0.219052, -0.247333, -0.214554, 0.16518, 0.055635, 0.0900204, 0.14286

r100
mxnet 
-0.08242247 -0.16276832 -0.19908722  0.13277343  0.07386855  0.20921 0.07552401  0.09261346 -0.05126226 -0.25519568]
tensorrt
-0.0824212, -0.162768, -0.199088, 0.132775, 0.0738689, 0.20921, 0.0755235, 0.0926148, -0.051263, -0.255196,
```

**Comment by ybw108** [comment]
I will try to figure this out as soon as possible.

**Comment by ybw108** [comment]
I use PReLU as activation function according to the orgin paper of MobileFaceNet, but I found the mxnet implementation from insightface uses LeakyRelu. I think that may cause output difference between mxnet and tensorrt implementation.

**Comment by irvingzhang0512** [comment]
@ybw108
I'm not familiar with mxnet. Correct me if I'm wroing. 

In `model-symbol.json`, it shows

```json
    {
      "op": "LeakyReLU", 
      "name": "dconv_23_conv_dw_relu", 
      "attrs": {"act_type": "prelu"}, 
      "inputs": [[36, 0, 0], [37, 0, 0]]
    }, 
```

Since the `act_type` is "prelu", after checking the mxnet [docs](https://mxnet.apache.org/versions/1.6.0/api/python/docs/api/symbol/op/index.html#mxnet.symbol.op.LeakyReLU), I believe  the mxnet version uses prelu as well.

**Comment by ybw108** [comment]
@irvingzhang0512 
Solved the problem by changing the `eps` value of `BatchNorm2d` layer in `conv_bn_relu()`, `conv_bn()` and `DepthWise()` from `2e-5` to `1e-3` (which is same to the mxnet implementation of mobilefacenet from insightface).
The first 10 elements of tensorrt and mxnet are almost the same now.
    
    mxnet
    0.01727602, -0.42228085, -0.07166053, 0.71358645, -0.12447035, 0.06586611, -0.168123, -0.13903172, 0.0436045, -0.22122546
    tensorrt
    0.017276246, -0.42228025, -0.071659051, 0.71358579, -0.12447044, 0.065866768, -0.16812359, -0.13903038, 0.043604929, -0.22122487
