### ISSUE TITLE
YOLOV5 trt_python inference error 

### ISSUE THREAD

**Issue by LIU-FAYANG** [wang-xinyu/tensorrtx#572]
Hi, i had this problem when i tried to use the python code to do inference, it shows something like 
serialization error. I tried to rebuild the engine and it still happens, any insights on this?

## Env

- GPU, e.g.Titan x 
- OS, e.g. Ubuntu18.04
- Cuda version 11.1
- TensorRT version 7.2.3

## Your problem
python3 yolov5_trt.py
- what is your command?

-[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +139, GPU +0, now: CPU 220, GPU 2463 (MiB)
[TensorRT] INFO: Loaded engine size: 44 MB
[TensorRT] INFO: [MemUsageSnapshot] deserializeCudaEngine begin: CPU 220 MiB, GPU 2463 MiB
[TensorRT] ERROR: 1: [stdArchiveReader.cpp::StdArchiveReader::34] Error Code 1: Serialization (Version tag does not match. Note: Current Version: 43, Serialized Engine Version: 96)
[TensorRT] ERROR: 4: [runtime.cpp::deserializeCudaEngine::74] Error Code 4: Internal Error (Engine deserialization failed.)
Traceback (most recent call last):
  File "yolov5_trt.py", line 373, in <module>
    yolov5_wrapper = YoLov5TRT(engine_file_path)
  File "yolov5_trt.py", line 88, in __init__
    context = engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
-------------------------------------------------------------------
PyCUDA ERROR: The context stack was not empty upon module cleanup.
-------------------------------------------------------------------
A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.
-------------------------------------------------------------------
Aborted (core dumped)

**Comment by wang-xinyu** [comment]
Where did you run ./yolov5 -s? Is it on the same platform?

**Comment by LIU-FAYANG** [comment]
Yes, I tried to serialize the engine on the same platform, I did it one more time to check and it still happened.

**Comment by wang-xinyu** [comment]
Does `./yolov5 -d` work fine?

**Comment by LIU-FAYANG** [comment]
Yes ./yolov5 -d works.

**Comment by wang-xinyu** [comment]
Probably, your python environments are not same as c++, including cuda, cudnn or trt.

**Comment by LIU-FAYANG** [comment]
Ahh yes, i used pip install nvidia-pyindex
pip install nvidia-tensorrt
 to install python-tensorrt, the package version is different from the c++ environment, any suggestion to solve this issue or how can i use the c++ trt environment to run the python code?

**Comment by wang-xinyu** [comment]
you can find .whl in tensorrt tar package. and use pip install .whl to install tensorrt for py.

**Comment by LIU-FAYANG** [comment]
Problem solved, simply use this: sudo apt-get install python3-libnvinfer-dev since I already have tensorrt installed.

**Comment by Lapierz** [comment]
Hi I am bumping this thread because I have the same issue.

**Error Code 1: Serialization (Serialization assertion safeVersionRead == safeSerializationVersion failed.Version tag does not match. Note: Current Version: 43, Serialized Engine Version: 96)**

GPU, e.g.gtx 970
OS, e.g. Ubuntu20.04
Cuda version 11.1
TensorRT version 8.0.1.6
and i have python3-libnvinfer-dev  installed.

**Comment by lzhhh6161** [comment]
> Hi I am bumping this thread because I have the same issue.
> 
> **Error Code 1: Serialization (Serialization assertion safeVersionRead == safeSerializationVersion failed.Version tag does not match. Note: Current Version: 43, Serialized Engine Version: 96)**
> 
> GPU, e.g.gtx 970
> OS, e.g. Ubuntu20.04
> Cuda version 11.1
> TensorRT version 8.0.1.6
> and i have python3-libnvinfer-dev installed.
I have the same issue, do you solve it ?

**Comment by lzhhh6161** [comment]
> Hi I am bumping this thread because I have the same issue.
> 
> **Error Code 1: Serialization (Serialization assertion safeVersionRead == safeSerializationVersion failed.Version tag does not match. Note: Current Version: 43, Serialized Engine Version: 96)**
> 
> GPU, e.g.gtx 970
> OS, e.g. Ubuntu20.04
> Cuda version 11.1
> TensorRT version 8.0.1.6
> and i have python3-libnvinfer-dev installed.

i have the same issue,do you solve it?

**Comment by pradeep-wyze** [comment]
I too have the same issue -- tried everything mentioned above.

**Comment by QingYuan-L** [comment]
i have the same issue when use triton inference serve 2107,tensorrt 2107(nvidia docker)

**Comment by p1x31** [comment]
You can solve this by providing latest engine version for LD_LIBRARY_PATH variable in your bashrc file:
```
echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"/usr/local/cuda-11.5/targets/x86_64-linux/lib:/urs/local/TensorRT-8.0.3.4/lib:/usr/local/cuda/lib:/usr/local/lib/python3.8/dist-packages/nvidia/cublas/lib:/usr/local/cuda-11.4/targets/x86_64-linux/lib"' >> ~/.bashrc
source ~/.bashrc
```
