### ISSUE TITLE
retinaface genwts.py : RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by Tetsujinfr** [wang-xinyu/tensorrtx#626]
## Env
- GPU jetson xavier nx
- OS Ubuntu18.04
- Cuda ver 10.2
- TensorRT version 7.1

## About this repo

- https://github.com/wang-xinyu/tensorrtx/tree/master/retinaface
- master branch

## Your problem

when running `python3 genwts.py`, I got the following error message:

> 
> File "genwts.py", line 12, in main
>      net = net.to(device)
>  ...
>  RuntimeError: CUDA error: invalid device ordinal
>

**Comment by Tetsujinfr** [comment]
after some googling, found the issue.
in genwts.py on line 10, the default gpu id is 1:
`    device = 'cuda:1'`

given I have only 1 gpu on the jetson, I changed the id to 0 and it worked fine:
`    device = 'cuda:0'`

I think it is a bit misleading to default the id to 1, assuming that the target system has at least 2 gpus, worth changing it I think or making a note in the reame to warn users. just my 2 centshere.

great repo anyway, thanks. closing.

**Comment by wang-xinyu** [comment]
Yes, should be cuda0 or cpu by default, can you raise a pr to fix it?

**Comment by jelling** [comment]
PR'ed: https://github.com/wang-xinyu/Pytorch_Retinaface/pull/2
