### ISSUE TITLE
yolov5-v6.0的模型在jatson-nano 上转engine失败

### ISSUE THREAD

**Issue by woshituobaye** [wang-xinyu/tensorrtx#791]
本人使用yolov5-v6.0版本训练了 yolov5s和yolov5n 模型，在jetson nano上将wst文件转到engine文件时，出现错误。
CUDA error 1 at /home/nvidia/Downloads/tensorrtx-jetson/yolov5/yololayer.cu:52yolov5: /home/nvidia/Downloads/tensorrtx-jetson/yolov5/yololayer.cu:52: virtual nvinfer1::YoloLayerPlugin::~YoloLayerPlugin(): Assertion `0' failed.
Aborted

**Comment by axxx-xxxa** [comment]
> 本人使用yolov5-v6.0版本训练了 yolov5s和yolov5n 模型，在jetson nano上将wst文件转到engine文件时，出现错误。 CUDA error 1 at /home/nvidia/Downloads/tensorrtx-jetson/yolov5/yololayer.cu:52yolov5: /home/nvidia/Downloads/tensorrtx-jetson/yolov5/yololayer.cu:52: virtual nvinfer1::YoloLayerPlugin::~YoloLayerPlugin(): Assertion `0' failed. Aborted

Same quesion in my comment .  Take a look .

**Comment by QQQTAO** [comment]
> > 本人使用yolov5-v6.0版本训练了 yolov5s和yolov5n 模型，在jetson nano上将wst文件转到engine文件时，出现错误。 CUDA error 1 at /home/nvidia/Downloads/tensorrtx-jetson/yolov5/yololayer.cu:52yolov5: /home/nvidia/Downloads/tensorrtx-jetson/yolov5/yololayer.cu:52: virtual nvinfer1::YoloLayerPlugin::~YoloLayerPlugin(): Assertion `0' failed. Aborted
> 
> Same quesion in my comment . Take a look .

pull the latest commit and try again.

**Comment by QQQTAO** [comment]
> > > 本人使用yolov5-v6.0版本训练了 yolov5s和yolov5n 模型，在jetson nano上将wst文件转到engine文件时，出现错误。 CUDA error 1 at /home/nvidia/Downloads/tensorrtx-jetson/yolov5/yololayer.cu:52yolov5: /home/nvidia/Downloads/tensorrtx-jetson/yolov5/yololayer.cu:52: virtual nvinfer1::YoloLayerPlugin::~YoloLayerPlugin(): Assertion `0' failed. Aborted
> > 
> > 
> > Same quesion in my comment . Take a look .
> 
> pull the latest commit and try again.

我听了作者的建议下载最新的代码解决了这个问题
