### ISSUE TITLE
CUDA error 222 when generating engine

### ISSUE THREAD

**Issue by larryKra** [wang-xinyu/tensorrtx#814]
## Env

- GPU, RTX3090
- OS,  Ubuntu18.04
- Cuda version 11.2
- TensorRT version 7

## About this repo

- which branch/tag/commit are you using?
- YOLOV5-5.0
- which model? yolov5, retinaface?
- yolov5

## Your problem
 ./yolov5 -s yolov5s.wts yolov5s.engine s
Loading weights: yolov5s.wts
CUDA error 222 at /home/tensorrtx/yolov5/yololayer.cu:37yolov5: /home/tensorrtx/yolov5/yololayer.cu:37: nvinfer1::YoloLayerPlugin::YoloLayerPlugin(int, int, int, int, const std::vector<Yolo::YoloKernel>&): Assertion `0' failed.
已放弃 (核心已转储)

- what is your command? e.g. `sudo ./yolov5 -s`
- ./yolov5 -s yolov5s.wts yolov5s.engine s
- what's your output?
- list above
- what output do you expect?

**Comment by wang-xinyu** [comment]
https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#different-versions-of-yolov5

**Comment by larryKra** [comment]
> https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#different-versions-of-yolov5

是根据上面的步骤来的，但是仍有上述错误

**Comment by jiangfeng94** [comment]
同样的问题 
    GPU, RTX3080
    OS, Ubuntu20.04
    Cuda version 11.3
    TensorRT version 8

**Comment by OOLLcnm** [comment]
CUDA11.3也有这个问题

**Comment by wang-xinyu** [comment]
这个问题已经解决了，确保用最新代码，包括gen_wts.py

**Comment by gaohandebaba** [comment]
请问是什么原因导致的呢，我用的是新的代码啊
