### ISSUE TITLE
pwgen::PwgenException

### ISSUE THREAD

**Issue by lihang2017** [wang-xinyu/tensorrtx#86]
$ sudo ./yolov3-spp -s
Loading weights: ../yolov3-spp_ultralytics68.wts
Building engine, please wait for a while...
terminate called after throwing an instance of 'pwgen::PwgenException'
  what():  Driver error: 
已放弃

请问这是什么原因

**Comment by wang-xinyu** [comment]
用的是ubuntu16.04吗

**Comment by lihang2017** [comment]
ubuntu18.04

**Comment by wang-xinyu** [comment]
那tensorrt安装的是ubuntu18.04的版本吗

**Comment by lihang2017** [comment]
是ubuntu18.04的版本
cuda-repo-ubuntu1804-10-2-local-10.2.89-440.33.01_1.0-1_amd64.deb
libcudnn7_7.6.5.32-1+cuda10.2_amd64.deb
nv-tensorrt-repo-ubuntu1804-cuda10.2-trt7.1.3.4-ga-20200617_1-1_amd64.deb

**Comment by wang-xinyu** [comment]
drive error,  看起来像是cuda和显卡驱动的问题

**Comment by lihang2017** [comment]
(base) lihang@lihang-Z390-UD:~$ nvidia-smi 
Wed Jul  8 17:33:38 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    On   | 00000000:01:00.0  On |                  N/A |
| 56%   47C    P8    10W / 175W |    280MiB /  7979MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1799      G   /usr/lib/xorg/Xorg                            18MiB |
|    0      1945      G   /usr/bin/gnome-shell                          49MiB |
|    0      4254      G   /usr/lib/xorg/Xorg                           125MiB |
|    0      4401      G   /usr/bin/gnome-shell                          83MiB |
+-----------------------------------------------------------------------------+

(base) lihang@lihang-Z390-UD:~$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

**Comment by wang-xinyu** [comment]
那不知道了，这个问题没见其他人遇到过，要不试试tensorrt官方例程能不能跑吧

**Comment by beizhengren** [comment]
@lihang2017 
您好，我遇到了同样的问题。请问您解决了吗？
我尝试了运行tensorrt官方的`sample_mnist`，也会报这个异常

**Comment by lihang2017** [comment]
@beizhengren 应该是显卡驱动和CUDA版本不匹配的问题，我换了一台服务器就可以用了

**Comment by beizhengren** [comment]
@lihang2017 谢谢！
那我可能得重装电脑了，哈哈

**Comment by infooptwang** [comment]
> @beizhengren 应该是显卡驱动和CUDA版本不匹配的问题，我换了一台服务器就可以用了

你好，请问哪个版本得显卡驱动和CUDA 10.2 能成功匹配啊

**Comment by beizhengren** [comment]
@infooptwang 440.64

**Comment by Eralien** [comment]
@infooptwang 
我的一开始装的是ubuntu-drivers devices里面的recommend版本，也有和你一样的问题。

我先卸载了驱动，然后手动重装了cuda-10.2的driver，就好了（从官网的runfile里面，不装toolkit什么的只装driver）
