### ISSUE TITLE
转yolov5s.engine失败

### ISSUE THREAD

**Issue by ghost** [wang-xinyu/tensorrtx#893]
## Env

- GPU, e.g. V100, RTX2080, TX2, Xavier NX, Nano, etc.
- OS, e.g. Ubuntu16.04, Win10, etc.
- Cuda version
- TensorRT version

## About this repo

- which branch/tag/commit are you using?
- which model? yolov5, retinaface?

## Your problem

CUDA error 222 at /home/zhaoqiuyu/project/yolo_trt/tensorrtx-master/yolov5/yololayer.cu:37yolov5: /home/zhaoqiuyu/project/yolo_trt/tensorrtx-master/yolov5/yololayer.cu:37: nvinfer1::YoloLayerPlugin::YoloLayerPlugin(int, int, int, int, const std::vector<Yolo::YoloKernel>&): Assertion `0' failed.
Aborted
请问产生这个问题的原因是什么啊？有回复用最新的代码，我用的是新版本的啊

**Comment by xjsxujingsong** [comment]
Any update? I have met the same issue in Windows using cuda 11.3 and TensorRT-8.2.2.1

**Comment by xjsxujingsong** [comment]
I debug and found the error is in
line 37 yololayer.cu
CUDA_CHECK(cudaMallocHost(&mAnchor, mKernelCount * sizeof(void*)));

**Comment by xjsxujingsong** [comment]
Hi I just fixed the problem. It is indeed the cuda problem. I have installed two version of cuda (11.1 and 11.3) and I switched to the other vision (11.1) and it worked.

**Comment by lefarcen** [comment]
> Hi I just fixed the problem. It is indeed the cuda problem. I have installed two version of cuda (11.1 and 11.3) and I switched to the other vision (11.1) and it worked.

Do you need to retrain after switching to cuda 11.1？

**Comment by xjsxujingsong** [comment]
> > Hi I just fixed the problem. It is indeed the cuda problem. I have installed two version of cuda (11.1 and 11.3) and I switched to the other vision (11.1) and it worked.
> 
> Do you need to retrain after switching to cuda 11.1？

No. I just used the default model.
