### ISSUE TITLE
[02/08/2022-19:45:19] [E] [TRT] 6: [libLoader.h::DynamicLibrary::49] Error Code 6: Internal Error (Unable to load library: libcublas.so.11)

### ISSUE THREAD

**Issue by GeneralJing** [wang-xinyu/tensorrtx#902]
docker环境内由于安装Python tensorrt的原因，装了cuda11，后来找到其他issue，使用tensorrt中的.whl重新装了tensorrt，但是再序列化engine文件的时候，不知道怎么依赖上cuda11了。cmakelist中配置的是10的路径：
cmake_minimum_required(VERSION 2.6)

project(yolov5)

add_definitions(-std=c++11)
add_definitions(-DAPI_EXPORTS)
option(CUDA_USE_STATIC_CUDA_RUNTIME OFF)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_BUILD_TYPE Debug)

find_package(CUDA REQUIRED)

if(WIN32)
enable_language(CUDA)
endif(WIN32)

include_directories(${PROJECT_SOURCE_DIR}/include)
# include and link dirs of cuda and tensorrt, you need adapt them if yours are different
# cuda
include_directories(/usr/local/cuda/include)
link_directories(/usr/local/cuda/lib64)
# tensorrt
include_directories(/usr/include/x86_64-linux-gnu/)
link_directories(/usr/lib/x86_64-linux-gnu/)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wall -Ofast -g -Wfatal-errors -D_MWAITXINTRIN_H_INCLUDED")
cuda_add_library(myplugins SHARED yololayer.cu)
target_link_libraries(myplugins nvinfer cudart)

find_package(OpenCV)
include_directories(${OpenCV_INCLUDE_DIRS})

cuda_add_executable(yolov5 calibrator.cpp yolov5.cpp preprocess.cu)

target_link_libraries(yolov5 nvinfer)
target_link_libraries(yolov5 cudart)
target_link_libraries(yolov5 myplugins)
target_link_libraries(yolov5 ${OpenCV_LIBS})

if(UNIX)
add_definitions(-O2 -pthread)
endif(UNIX)

所以不太理解，是cuda11改了本地什么配置了吗？

**Comment by Ziming-Zhang** [comment]
你好我现在也遇到了同样的问题，请问您后来有解决方法了吗

**Comment by GeneralJing** [comment]
挺久了，记得不是很清楚了，好像是重新建了一个docker环境

**Comment by Ziming-Zhang** [comment]
> 挺久了，记得不是很清楚了，好像是重新建了一个docker环境

嗯嗯，我后来又下了个低的tensorrt版本就好了，应该是libcublasLt的版本没对上
